### ISSUE TITLE
ask for id annotation of CelebA

### ISSUE THREAD

**Issue by breadbread1984** [liuziwei7/mobile-id#7]
I want to implement mobile-id myself. I found that the identity annotation of CelebA is only available upon request. I pledge I will only use it for research purpose. Thx. my email is [address](mailto://breadbread1984@163.com)

**Comment by JMT800** [comment]
hello @breadbread1984 , did you receive the ids regarding the celebA dataset !?

**Comment by liuziwei7** [comment]
The identity annotation is already available in the CelebA dataset "Anno" folder: https://drive.google.com/open?id=0B7EVK8r0v71pWEZsZE9oNnFzTm8 .

**Comment by JMT800** [comment]
Thank you @liuziwei7  for the quick reply, but what i meant by ids --> Full name of the celebrity ! i checked the link you sent and saw an identity annotation's text file however each image is mapped to an integer but not the full name of the celebrity. Is there any way we can get the Full name of the celebrity in each picture?  thank you for your help,
